-- ============================================================
-- SPORTS ACADEMIES EXTRACTOR & DISCOVERY - COMPLETE DATABASE SCHEMA
-- Run this in your Supabase SQL Editor (SQL Editor -> New Query -> Run)
-- ============================================================

-- 1. DISCOVERY RUNS
CREATE TABLE IF NOT EXISTS discovery_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    total_queries INTEGER NOT NULL DEFAULT 0,
    total_results INTEGER NOT NULL DEFAULT 0,
    total_candidates INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. DISCOVERY CANDIDATES
CREATE TABLE IF NOT EXISTS discovery_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovery_run_id BIGINT NOT NULL REFERENCES discovery_runs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    domain TEXT NOT NULL,
    snippet TEXT,
    discovery_strategy TEXT,
    discovery_query TEXT,
    discovered_from TEXT,
    source_type TEXT,
    candidate_type TEXT,
    is_official_source BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discovery_candidates_run ON discovery_candidates(discovery_run_id);
CREATE INDEX IF NOT EXISTS idx_discovery_candidates_domain ON discovery_candidates(domain);

-- 3. CRAWL RUNS
CREATE TABLE IF NOT EXISTS crawl_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovery_candidate_id BIGINT REFERENCES discovery_candidates(id) ON DELETE SET NULL,
    start_url TEXT NOT NULL,
    max_depth INTEGER,
    max_pages INTEGER,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    total_pages_visited INTEGER NOT NULL DEFAULT 0,
    total_pages_failed INTEGER NOT NULL DEFAULT 0,
    total_scholarships_extracted INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crawl_runs_status ON crawl_runs(status);

-- 4. CRAWL PAGES
CREATE TABLE IF NOT EXISTS crawl_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_run_id BIGINT NOT NULL REFERENCES crawl_runs(id) ON DELETE CASCADE,
    parent_page_id BIGINT REFERENCES crawl_pages(id) ON DELETE SET NULL,
    url TEXT NOT NULL,
    final_url TEXT,
    depth INTEGER NOT NULL DEFAULT 0,
    title TEXT,
    status_code INTEGER,
    page_type TEXT,
    crawl_status TEXT NOT NULL DEFAULT 'PENDING',
    crawl_action TEXT,
    skip_reason TEXT,
    links_found INTEGER NOT NULL DEFAULT 0,
    links_queued INTEGER NOT NULL DEFAULT 0,
    scholarships_extracted INTEGER NOT NULL DEFAULT 0,
    extraction_method TEXT,
    decision_metadata JSONB,
    error_message TEXT,
    crawled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crawl_pages_run ON crawl_pages(crawl_run_id);
CREATE INDEX IF NOT EXISTS idx_crawl_pages_url ON crawl_pages(url);

-- 5. SCHOLARSHIPS / SPORTS ACADEMIES
CREATE TABLE IF NOT EXISTS scholarships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_run_id BIGINT REFERENCES crawl_runs(id) ON DELETE SET NULL,
    crawl_page_id BIGINT REFERENCES crawl_pages(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    organization TEXT,
    scheme_type TEXT,
    application_start DATE,
    application_end DATE,
    source_url TEXT NOT NULL,
    guidelines_url TEXT,
    faq_url TEXT,
    application_url TEXT,
    scholarship_amount TEXT,
    education_level TEXT,
    income_criteria TEXT,
    gender_criteria TEXT,
    category_criteria TEXT,
    domicile TEXT,
    eligibility_summary TEXT,
    documents_required TEXT,
    selection_process TEXT,
    computed_status TEXT DEFAULT 'ACTIVE',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scholarships_title ON scholarships(title);
CREATE INDEX IF NOT EXISTS idx_scholarships_source_url ON scholarships(source_url);
CREATE INDEX IF NOT EXISTS idx_scholarships_computed_status ON scholarships(computed_status);
CREATE INDEX IF NOT EXISTS idx_scholarships_is_active ON scholarships(is_active);

-- 6. SCHOLARSHIP VALIDATIONS
CREATE TABLE IF NOT EXISTS scholarship_validations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scholarship_id BIGINT NOT NULL REFERENCES scholarships(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    legitimacy_score INTEGER NOT NULL CHECK (legitimacy_score >= 0 AND legitimacy_score <= 100),
    confidence NUMERIC(4,3) CHECK (confidence >= 0 AND confidence <= 1),
    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    verification_checks JSONB NOT NULL DEFAULT '[]'::JSONB,
    warnings JSONB NOT NULL DEFAULT '[]'::JSONB,
    source_snapshot JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scholarship_validations_scholarship ON scholarship_validations(scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_validations_score ON scholarship_validations(legitimacy_score);

-- 7. SCHOLARSHIP CHANGES
CREATE TABLE IF NOT EXISTS scholarship_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scholarship_id BIGINT NOT NULL REFERENCES scholarships(id) ON DELETE CASCADE,
    field_name TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    change_type TEXT NOT NULL DEFAULT 'FIELD_UPDATED',
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scholarship_changes_scholarship ON scholarship_changes(scholarship_id);
